### ISSUE TITLE
Table header resiliency

### ISSUE THREAD

**Issue by auniverseaway** [adobe/da-collab#49]
As an author, I would like the editor / collab to not error out if my table header is malformed so that I can correctly preview my content.

### Criteria of acceptance
1. Editor / Collab / Hast / YJS can handle a table header (td or th) without any text.
2. Editor / Collab / Hast / YJS can handle a table header (td or th) with two columns.

### Additional context
I _think the fix [is here](https://github.com/adobe/da-collab/blob/main/src/collab.js#L398).

**Comment by bosschaert** [comment]
I was able to reproduce the issue. On this part:

> 2. Editor / Collab / Hast / YJS can handle a table header (td or th) with two columns.

the problem happens when the first column in the header is left empty
